language: python

cache: pip

matrix:
    include:
    - os: linux
      python: '2.7'
    - os: linux
      python: '3.3'
    - os: linux
      python: '3.5'
    - os: linux
      python: '2.7'
      env: XAPIAN='true';
    - os: linux
      python: '3.5'
      env: XAPIAN='true';

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # needed to build Xapian
    - uuid-dev
    - gcc-4.8
    - g++-4.8

install:
  - pip install -r setup/requirements.txt
  - pip install sphinx
  - "if [[ $XAPIAN == 'true' ]]; then CXX=g++-4.8 ./setup/install-xapian.sh; fi"
  - "if [[ $XAPIAN == 'true' ]]; then echo 'default_indexer: \'xapian\'' > local_settings.yml; fi"

script:
  - python main.py --test
