###Things to add in the /etc/elasticsearch/elasticsearch.yml

node.name: "YourServer"

##################################### Analyzer ################################
index :
  analysis :
    analyzer :
      default_index :
        type : custom
        tokenizer : kuromoji_tokenizer
      romaji_analyzer :
        tokenizer : kuromoji_tokenizer
        filter : romaji_readingform
      katakana_analyzer :
        tokenizer : kuromoji_tokenizer
        filter : katakana_readingform
    filter :
      romaji_readingform :
        type : kuromoji_readingform
        use_romaji : true
      katakana_readingform :
        type : kuromoji_readingform
        use_romaji : false

